apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-cicd
  description: "Simple Java project for Tekton Pipeline Demo."
  tags:
    - tekton
    - cicd
    - demo
    - java
  annotations:
    github.com/project-slug: letuyenuit/tekton-demo
spec:
  type: website
  lifecycle: experimental
  owner: User:guest
